### ISSUE TITLE
python import exception on ansible 2.2.0

### ISSUE THREAD

**Issue by gzm55** [bfmartin/ansible-sshknownhosts-role#5]
bash-4.3# cat pl.yml 
- hosts: all
  gather_facts: False
  connection: local
  vars:
    ssh_known_hosts:
      - dest: /etc/ssh/ssh_known_hosts
  roles:
    - role: bfmartin.ssh_known_hosts

ansible-playbook -vvv -i inv pl.yml

An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 88, in run
    items = self._get_loop_items()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 186, in _get_loop_items
    loop_terms = listify_lookup_plugin_terms(terms=self._task.loop_args, templar=templar, loader=self._loader, fail_on_undefined=True, convert_bare=False)
  File "/usr/lib/python2.7/site-packages/ansible/utils/listify.py", line 34, in listify_lookup_plugin_terms
    terms = templar.template(terms.strip(), convert_bare=convert_bare, fail_on_undefined=fail_on_undefined)
  File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 336, in template
    eval_results = safe_eval(result, locals=self._available_variables, include_exceptions=True)
  File "/usr/lib/python2.7/site-packages/ansible/template/safe_eval.py", line 104, in safe_eval
    for test in test_loader.all():
  File "/usr/lib/python2.7/site-packages/ansible/plugins/__init__.py", line 381, in all
    for i in self._get_paths():
  File "/usr/lib/python2.7/site-packages/ansible/plugins/__init__.py", line 184, in _get_paths
    ret.extend(self._get_package_paths())
  File "/usr/lib/python2.7/site-packages/ansible/plugins/__init__.py", line 157, in _get_package_paths
    m = __import__(self.package)
ImportError: No module named test

**Comment by bfmartin** [comment]
Is there a value for "name"? I don't see it in your pl.yml file.

Try adding that as it is a required parameter.

The name is a remote host to contact to get its host key.

**Comment by bfmartin** [comment]
Closing for now. Let me know if this sill happens,

**Comment by gzm55** [comment]
This is a bug by my mistake. Thanks for reviewing and closing this issue.

**Comment by yuanzhuangl** [comment]
> This is a bug by my mistake. Thanks for reviewing and closing this issue.

Could you let me know how do you fix this, I am having the same issue now, thanks!

**Comment by gzm55** [comment]
as i can remember, the `test` operator dir in ansible was removed by mistake.

**Comment by bfmartin** [comment]
Have you fixed it? If not, can you share your error messages, along with the Ansible version, along with your OS and version for server and client?

**Comment by gzm55** [comment]
the bug was introduced by a buggy Dockerfile, and fixed just by keeping the `test/` dir. About 4 years ago, the ansible should be about 2.0, os is alpine.
